struct VSInput {
    float2 inPosition;
    float3 inColor;
};

struct VSOutput {
    float3 color;
    float4 position : SV_Position;
};

[shader("vertex")]
VSOutput vertMain(VSInput input) {
    VSOutput output;
    output.position = float4(input.inPosition, 0.0, 1.0);
    output.color = input.inColor;
    return output;
}

[shader("fragment")]
float4 fragMain(VSOutput inVert) : SV_Target {
    return float4(inVert.color, 1.0);
}